name: testsuite

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
        # include:
        #   - os: windows-2019
        #     python-version: 3.4
        #   - os: windows-2019
        #     python-version: 3.4
        #   - os: macos-10.14
        #     python-version: 3.4

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mock
          pip install pytest
      - name: Test with pytest
        run: |
          pytest
      - name: check whether the package is installable and usable
        run: |
          organize list
          organize config --path
          organize --version
